"""
governance - AgentOps governance layer: trace, guardrail, evaluation, monitoring, dashboard

Author: le
Date: 2026/7/29
Version: 0.2
Task: Governance package initialization
"""
from __future__ import annotations

from governance.pii import (
    PIIType,
    PIIMatch,
    PIIResult,
    batch_detect_and_mask,
    detect_and_mask,
    detect_bank_cards,
    detect_emails,
    detect_id_cards,
    detect_phones,
    detect_pii,
    mask_bank_card,
    mask_email,
    mask_id_card,
    mask_phone,
    mask_pii,
)
from governance.guardrail import (
    GuardrailResult,
    GuardrailRunner,
    GuardType,
    GuardSeverity,
    GuardFinding,
    check_input,
    check_output,
    check_injection,
    check_sensitive,
    check_pii_in_input,
    check_error_leak,
    check_secret_leak,
    check_prompt_leak,
    filter_output,
    quick_check_input,
    quick_check_output,
)
from governance.trace import (
    SpanKind,
    SpanStatus,
    TraceInfo,
    SpanRecord,
    SpanInProgress,
    TraceRecorder,
    AgentTracer,
    get_current_trace,
    set_current_trace,
    start_trace,
    end_trace,
    record_llm_usage,
    record_tool_call as trace_record_tool_call,
    get_trace_recorder,
    reset_trace_recorder,
)
from governance.monitor import (
    MetricType,
    Metric,
    MetricValue,
    MetricsCollector,
    get_collector,
    reset_collector,
    record_agent_call,
    record_tool_call as monitor_record_tool_call,
    get_metrics_snapshot,
    export_prometheus_metrics,
)
from governance.dashboard import (
    AgentStat,
    EvalTrendPoint,
    VersionComparison,
    DashboardSummary,
    DashboardDataProvider,
    get_dashboard_provider,
    reset_dashboard_provider,
    get_dashboard_summary,
)
from governance.evaluation import (
    # Metrics
    RAGMetricResult,
    AgentMetricResult,
    EvalReport,
    compute_faithfulness,
    compute_answer_relevance,
    compute_context_recall,
    compute_rag_metrics,
    compute_task_success_rate,
    compute_tool_accuracy,
    compute_tool_accuracy_from_mcp_history,
    compute_avg_latency_ms,
    compute_avg_step_count,
    compute_agent_metrics,
    compute_intent_accuracy,
    compute_intent_accuracy_batch,
    compute_overall_score,
    # Evaluator
    EvaluationEngine,
    EvaluationResult,
    EvalCaseRecord,
    evaluate_from_json_file,
    # Benchmark
    BenchmarkResult,
    BenchmarkRunner,
    GoldenDataset,
    run_default_benchmark,
    # Runner
    RunnerConfig,
    RunnerResult,
    EvalRunner,
    ReportWriter,
    build_cli_parser,
    main,
    cli_main,
)

__all__ = [
    # ── PII ──
    "PIIType",
    "PIIMatch",
    "PIIResult",
    "mask_phone",
    "mask_id_card",
    "mask_email",
    "mask_bank_card",
    "mask_pii",
    "detect_phones",
    "detect_id_cards",
    "detect_emails",
    "detect_bank_cards",
    "detect_pii",
    "detect_and_mask",
    "batch_detect_and_mask",
    # ── Guardrail ──
    "GuardrailResult",
    "GuardrailRunner",
    "GuardType",
    "GuardSeverity",
    "GuardFinding",
    "check_input",
    "check_output",
    "check_injection",
    "check_sensitive",
    "check_pii_in_input",
    "check_error_leak",
    "check_secret_leak",
    "check_prompt_leak",
    "filter_output",
    "quick_check_input",
    "quick_check_output",
    # ── Trace ──
    "SpanKind",
    "SpanStatus",
    "TraceInfo",
    "SpanRecord",
    "SpanInProgress",
    "TraceRecorder",
    "AgentTracer",
    "get_current_trace",
    "set_current_trace",
    "start_trace",
    "end_trace",
    "record_llm_usage",
    "trace_record_tool_call",
    "get_trace_recorder",
    "reset_trace_recorder",
    # ── Monitor ──
    "MetricType",
    "Metric",
    "MetricValue",
    "MetricsCollector",
    "get_collector",
    "reset_collector",
    "record_agent_call",
    "monitor_record_tool_call",
    "get_metrics_snapshot",
    "export_prometheus_metrics",
    # ── Dashboard ──
    "AgentStat",
    "EvalTrendPoint",
    "VersionComparison",
    "DashboardSummary",
    "DashboardDataProvider",
    "get_dashboard_provider",
    "reset_dashboard_provider",
    "get_dashboard_summary",
    # ── Evaluation ──
    "RAGMetricResult",
    "AgentMetricResult",
    "EvalReport",
    "compute_faithfulness",
    "compute_answer_relevance",
    "compute_context_recall",
    "compute_rag_metrics",
    "compute_task_success_rate",
    "compute_tool_accuracy",
    "compute_tool_accuracy_from_mcp_history",
    "compute_avg_latency_ms",
    "compute_avg_step_count",
    "compute_agent_metrics",
    "compute_intent_accuracy",
    "compute_intent_accuracy_batch",
    "compute_overall_score",
    "EvaluationEngine",
    "EvaluationResult",
    "EvalCaseRecord",
    "evaluate_from_json_file",
    "BenchmarkResult",
    "BenchmarkRunner",
    "GoldenDataset",
    "run_default_benchmark",
    "RunnerConfig",
    "RunnerResult",
    "EvalRunner",
    "ReportWriter",
    "build_cli_parser",
    "main",
    "cli_main",
]
